name: Crowd Control
main: org.elbukkit.crowdcontrol.CrowdControlPlugin
version: 0.0.1
author: Andrew Querol
description: Creature control
commands:
  kill:
    description: Kills entities
    usage: |
           /<command> [all,entity name]
