package com.elbukkit.plugins.crowd.events;

import java.util.EventObject;

import org.bukkit.Location;
import org.bukkit.entity.CreatureType;
import org.bukkit.event.Cancellable;

/**
 * A simple event for creature spawning generated by my custom system
 * 
 * @author Andrew Querol(winsock)
 * @version 1.0
 */
public class CreatureSpawnEvent extends EventObject implements Cancellable {
    private static final long serialVersionUID = -5031301408889128018L;
    private boolean canceled = false;
    private Location location;
    private CreatureType type;

    public CreatureSpawnEvent(Object sender, Location location, CreatureType type) {
        super(sender);

        this.location = location;
        this.type = type;
    }

    /**
     * Gets the location of the spawning
     * 
     * @return {@link Location}
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Gets the type of creature that wants to spawn
     * 
     * @return {@link CreatureType}
     */
    public CreatureType getType() {
        return type;
    }

    /**
     * Gets if the event was canceled
     * 
     * @return {@link Boolean}
     */
    public boolean isCancelled() {
        return canceled;
    }

    /**
     * Sets if the event is canceled
     * 
     * @param cancel
     *            {@link Boolean}
     */
    public void setCancelled(boolean cancel) {
        this.canceled = cancel;
    }
}
