package com.elbukkit.plugins.crowd.events;

import java.util.EventListener;

/**
 * A simple event listener for creature events generated by my plugin
 * 
 * @author Andrew Querol(winsock)
 * @version 1.0
 */
public interface CrowdListener extends EventListener {
    void onCreatureAttack(CreatureAttackEvent event);
    
    void onCreatureMove(CreatureMoveEvent event);
    
    void onCreatureSpawn(CreatureSpawnEvent event);
}
