name: CrowdControl
main: com.elBukkit.bukkit.plugins.crowd.CrowdControlPlugin
version: 0.22
website: http://mine.elmakers.com
author: elBukkit
description : Simple console-based creature control
commands:
  crowd:
    description: Control mob spawning
    usage: crowd [add,finish,listPending,listEnabled,rebuildDB,listRules,getDetailedInfo] 
                
                