name: CrowdControl
main: com.elBukkit.plugins.crowd.CrowdControlPlugin
version: 0.26.02
website: https://github.com/elBukkit/CrowdControlPlugin
author: elBukkit
description : Simple console-based creature control
commands:
  crowd:
    description: Control mob spawning
    usage: crowd [add,finish,listPending,listEnabledRules,rebuildDB,listRules,getDetailedInfo]     