name: CrowdControl
main: com.elbukkit.plugins.crowd.CrowdControlPlugin
version: 0.27.04
website: https://github.com/elBukkit/CrowdControlPlugin
author: elBukkit
description : Simple console-based creature control
depends: [elRegions]
commands:
  crowd:
    description: Control mob spawning
    usage: crowd [add,finish,listPending,listEnabledRules,reloadConfig,listRules]     