mobs:
    CHICKEN:
        enabled: false
        nature:
            night: PASSIVE
            day: PASSIVE
        damage: 0
        targetDistance: 24
        health: 4
        burnDay: false
        spawnChance: 0.7
    COW:
        enabled: false
        nature:
            night: PASSIVE
            day: PASSIVE
        damage: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    CREEPER:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage: 20
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    GHAST:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage: 5
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.1
    GIANT:
        enabled: false
        nature:
            night: PASSIVE
            day: PASSIVE
        damage: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.1
    MONSTER:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage: 1
        targetDistance: 24
        health: 20
        burnDay: false
        spawnChance: 0.1
    PIG:
        enabled: false
        nature:
            night: PASSIVE
            day: PASSIVE
        damage: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    PIG_ZOMBIE:
        enabled: true
        nature:
            night: NEUTRAL
            day: NEUTRAL
        damage: 5
        targetDistance: 24
        health: 20
        burnDay: false
        spawnChance: 0.7
    SHEEP:
        enabled: false
        nature:
            night: PASSIVE
            day: PASSIVE
        damage: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    SKELETON:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage: 4
        targetDistance: 24
        health: 10
        burnDay: true
        spawnChance: 0.7
    SLIME:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage: 4 # Slime damage is the arithmetic series 2n, n = slimeSize - 1
        targetDistance: 24
        health: 1 # Slime health is the geometric series 3^n. n = slimeSize - 1
        burnDay: false
        spawnChance: 0.05
    SPIDER:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: NEUTRAL
        damage: 5
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    SQUID:
        enabled: false
        nature:
            night: PASSIVE
            day: PASSIVE
        damage: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.1
    ZOMBIE:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage: 5
        targetDistance: 24
        health: 10
        burnDay: true
        spawnChance: 0.7
    WOLF:
        enabled: false
        nature:
            night: PASSIVE
            day: PASSIVE
        damage: 5
        targetDistance: 24
        health: 20
        burnDay: false
        spawnChance: 0.1
        
rules:
    CHICKEN:
    COW:
    CREEPER:
    GHAST:
        SpawnMaterialRule:
            Default:
                material:
                    - AIR
                spawnable: true
    GIANT:
    MONSTER:
    PIG:
    PIG_ZOMBIE:
        SpawnMaterialRule:
            Default:
                material:
                    - NETHERRACK
                    - SOUL_SAND
                spawnable: true
    SHEEP:
    SKELETON:
    SLIME:
    SPIDER:
    SQUID:
    ZOMBIE:
    WOLF: