mobs:
    CHICKEN:
        enabled: true
        nature:
            night: PASSIVE
            day: PASSIVE
        damage:
            collision: 0
            misc: 0
        targetDistance: 24
        health: 4
        burnDay: false
        spawnChance: 0.7
    COW:
        enabled: true
        nature:
            night: PASSIVE
            day: PASSIVE
        damage:
            collision: 0
            misc: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    CREEPER:
        enabled: true
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage:
            collision: 0
            misc: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    GHAST:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage:
            collision: 0
            misc: 5
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    GIANT:
        enabled: false
        nature:
            night: PASSIVE
            day: PASSIVE
        damage:
            collision: 0
            misc: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    MONSTER:
        enabled: false
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage:
            collision: 1
            misc: 0
        targetDistance: 24
        health: 20
        burnDay: false
        spawnChance: 0.1
    PIG:
        enabled: true
        nature:
            night: PASSIVE
            day: PASSIVE
        damage:
            collision: 0
            misc: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    PIG_ZOMBIE:
        enabled: false
        nature:
            night: NEUTRAL
            day: NEUTRAL
        damage:
            collision: 5
            misc: 0
        targetDistance: 24
        health: 20
        burnDay: false
        spawnChance: 0.7
    SHEEP:
        enabled: true
        nature:
            night: PASSIVE
            day: PASSIVE
        damage:
            collision: 0
            misc: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    SKELETON:
        enabled: true
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage:
            collision: 0
            misc: 4
        targetDistance: 24
        health: 10
        burnDay: true
        spawnChance: 0.7
    SLIME:
        enabled: true
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage:
            collision: 4
            misc: 0
        targetDistance: 24
        health: 1 # Slime health is the geometric series 3^n. N = slimeSize - 1
        burnDay: false
        spawnChance: 0.2
    SPIDER:
        enabled: true
        nature:
            night: AGGRESSIVE
            day: NEUTRAL
        damage:
            collision: 0
            misc: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.7
    SQUID:
        enabled: true
        nature:
            night: PASSIVE
            day: PASSIVE
        damage:
            collision: 0
            misc: 0
        targetDistance: 24
        health: 10
        burnDay: false
        spawnChance: 0.5
    ZOMBIE:
        enabled: true
        nature:
            night: AGGRESSIVE
            day: AGGRESSIVE
        damage:
            collision: 5
            misc: 0
        targetDistance: 24
        health: 10
        burnDay: true
        spawnChance: 0.7
    WOLF:
        enabled: true
        nature:
            night: PASSIVE
            day: PASSIVE
        damage:
            collision: 5
            misc: 0
        targetDistance: 24
        health: 20
        burnDay: false
        spawnChance: 0.4
        
rules:
    CHICKEN:
    COW:
    CREEPER:
    GHAST:
    GIANT:
        SpawnMaterialRule:
            Default:
                material:
                    - AIR
                spawnable: true
    MONSTER:
    PIG:
    PIG_ZOMBIE:
        SpawnMaterialRule:
            Default:
                material:
                    - NETHERRACK
                    - SOUL_SAND
                spawnable: true
    SHEEP:
    SKELETON:
    SLIME:
    SPIDER:
    SQUID:
    ZOMBIE:
    WOLF: