package com.elBukkit.bukkit.plugins.crowd.events;

import java.util.EventListener;

/*
 * A simple event listener for creature events generated by my plugin
 * 
 * @author Andrew Querol(winsock)
 */

public interface CrowdListener extends EventListener {
	public void onCreatureAttack(CreatureAttackEvent event);

	public void onCreatureMove(CreatureMoveEvent event);

	public void onCreatureSpawn(CreatureSpawnEvent event);
}
